### ISSUE TITLE
Enable pre-training by initializing new model with previously trained weights

### ISSUE THREAD

**Issue by rak5216** [mit-quest/necstlab-damage-segmentation#32]

**Comment by rak5216** [comment]
@Josh-Joseph do you think this will be a quick task for the next issue to tackle? Perhaps on the command line for training we can give a new parameter like `--pre-trained-weights <model_ID>`, with default being no pre-training when the parameter is excluded. Then it just loads in this model and starts epoch 1 with that.

**Comment by CarolinaFurtado** [comment]
Branch: **issue_32_init_pretrained_weigths**

Modified **train_segmetation_model.py:** 
- added a **new arg**: model_id_start, default to none
- if model_id_start not none (a pretrained model is used to initialize the weights): 
      - copy model locally 
      - compiled_model.weights_to_load = Path(local_model_dir, model_id_start, "model.hdf5").as_posix()

It runs, both with and without the model_id_start argument. Not sure if is doing the right thing yet. 

Still need to modify the metadata file to say where the initial weights come from.

**Comment by CarolinaFurtado** [comment]
Added the pretrained model to the metadata file: 

```
created_datetime: 20201019T164941Z
dataset_config:
  class_annotation_mapping:
    class_0_annotation_GVs: [100]
    class_1_annotation_GVs: [175]
    class_2_annotation_GVs: [250]
  dataset_split:
    test: [8bit_AS4_S2_P1_L6_2560_1750_2160]
    train: [THIN_REF_S2_P1_L3_2496_1563_2159]
    validation: [THIN_CNT_S2_P1_L4_2334_1578_2159]
  image_cropping:
    min_num_class_pos_px: {class_0_pos_px: 5, class_1_pos_px: 5, class_2_pos_px: 5}
    num_neg_per_class: 1
    num_per_image: None
    num_pos_per_class: 1
    type: class
  stack_downsampling: {num_skip_beg_slices: 50, num_skip_end_slices: 50, number_of_images: 100,
    type: linear}
  target_size: &id001 [512, 512]
elapsed_minutes: 8.6
gcp_bucket: gs://necstlab-sandbox
git_hash: 692429e0290544b2652339fb4e8e99050054e591
global_threshold_for_metrics: 0.5
num_classes: 3
original_config_filename: configs/config_sandbox/tf_version_debug//train-small-3class_tfversion_debug.yaml
**pre_trained_model_config:
  batch_size: 16
  data_augmentation: {random_90-degree_rotations: false}
  dataset_id: dataset-small-3class_tfversion_debug
  epochs: 10
  loss: cross_entropy
  model_id_prefix: segmentation-model-small-3class_tfversion_debug
  optimizer: adam
  segmentation_model:
    model_name: Unet
    model_parameters: {backbone_name: vgg16, encoder_weights: null}
  test_data_shuffle_seed: 123456
  training_data_shuffle_seed: 1234
  validation_data_shuffle_seed: 12345
pre_trained_model_id: segmentation-model-small-3class_tfversion_debug_20201016T164701Z**
target_size: *id001
```

**Comment by CarolinaFurtado** [comment]
If we train a model: 
`python3 train_segmentation_model.py --gcp-bucket gs://necstlab-sandbox --config-file configs/config_sandbox/tf_version_debug//train-small-3class_tfversion_debug.yaml `

 and then train a model starting with the first models pretrained weights: 

`python3 train_segmentation_model.py --gcp-bucket gs://necstlab-sandbox --config-file configs/config_sandbox/tf_version_debug//train-small-3class_tfversion_debug.yaml --pre-trained-model-id segmentation-model-small-3class_tfversion_debug_20201019T174848Z
`

This is what we get: - the second model continuous training with the loss of the previously trained model: 
![image](https://user-images.githubusercontent.com/43469359/96499003-cc3e0b80-121a-11eb-93a2-f3dcc20a06c2.png)

**Comment by CarolinaFurtado** [comment]
If we train two models from the first trained models: 
`python3 train_segmentation_model.py --gcp-bucket gs://necstlab-sandbox --config-file configs/config_sandbox/tf_version_debug//train-small-3class_tfversion_debug.yaml --pre-trained-model-id segmentation-model-small-3class_tfversion_debug_20201019T174848Z
`
![image](https://user-images.githubusercontent.com/43469359/96499015-d3fdb000-121a-11eb-93e0-10c7580b91a8.png)

we obtain very similar loss evolutions. The starting point is the same, evolution is very similar but not exactly the same. All the possible (known) source of randomness is eliminated,   `training_data_shuffle_seed`, `validation_data_shuffle_seed` and  `test_data_shuffle_seed` and `random_90-degree_rotations`: 

```
train_config:
  model_id_prefix: 'segmentation-model-small-3class_tfversion_debug'
  dataset_id: 'dataset-small-3class_tfversion_debug'
  segmentation_model:
    model_name: 'Unet'
    model_parameters:
      backbone_name: 'vgg16'
      encoder_weights: Null   # Null (random initialization) or 'imagenet' (pre-training on ImageNet)
  loss: 'cross_entropy'
  optimizer: 'adam'
  batch_size: 16    # p100
  epochs: 10
  training_data_shuffle_seed: 1234
  validation_data_shuffle_seed: 12345
  test_data_shuffle_seed: 123456
  data_augmentation:
    random_90-degree_rotations: False
```
