### ISSUE TITLE
decide and implement either 1 class or multi-class support across the repo

### ISSUE THREAD

**Issue by Josh-Joseph** [mit-quest/necstlab-damage-segmentation#7]
```
    class_0: ['0-degree_damage', '45-degree_damage', '90-degree_damage']
```

**Comment by rak5216** [comment]
```
  class_annotation_mapping:
    class_0: [100, 175, 250]  # '0-degree_damage', '45-degree_damage', '90-degree_damage'

  class_annotation_mapping:
    class_0_annotation_GVs: [100]
    class_1_annotation_GVs: [175]
    class_2_annotation_GVs: [250]

```
